services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB_AUTHSERVER}
      POSTGRES_USER: ${PG_DB_AUTHSERVER_USER}
      POSTGRES_PASSWORD: ${PG_DB_AUTHSERVER_PASSWORD}
    ports:
      - "${PG_DB_AUTHSERVER_EXTERNAL_PORT}:5432"
    volumes:
      - pgdata_AUTHSERVER:/var/lib/postgresql/data

volumes:
  pgdata_AUTHSERVER: