services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB_AUTHSERVER}
      POSTGRES_USER: ${PG_DB_AUTHSERVER_USER}
      POSTGRES_PASSWORD: ${PG_DB_AUTHSERVER_PASSWORD}
    ports:
      - "${PG_DB_AUTHSERVER_EXTERNAL_PORT}:5432"
    volumes:
      - authserver_pgdata_AUTHSERVER:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: ${PG_DB_AUTHSERVER}
      DB_USER: ${PG_DB_AUTHSERVER_USER}
      DB_PASSWORD: ${PG_DB_AUTHSERVER_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${PG_DB_AUTHSERVER}
      KC_DB_USERNAME: ${PG_DB_AUTHSERVER_USER}
      KC_DB_PASSWORD: ${PG_DB_AUTHSERVER_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT}:8080"
    depends_on:
      - db
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--hostname=localhost"]

volumes:
  authserver_pgdata_AUTHSERVER:
